# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46d42dc34d51808738005e098dd9c8677d06cd88830396deec02f9d3d9d2916e67915bd715626a1a67abdae4fc70138150a216fa08a8e94fe746d9abbf7b9945

test:
  secret_key_base: 8547c1c11168ea871251f2dcf3f30b2bc837d973ce4d43e2d05a037ce3b512d6165e93e1834a9ca9aff0e736c8c4e088b69b361dc044d1d0f2fccdc859033848

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
